<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <LangVersion>Latest</LangVersion>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.1.0</Version>
    <MainEntryPoint>YYHEggEgg.EasyProtobuf.EasyProtobufProgram</MainEntryPoint>
    <RootNamespace>YYHEggEgg.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Protobuf-*/**" />
    <EmbeddedResource Remove="Protobuf-**/**" />
    <None Remove="Protobuf-*/**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Protobuf-*/**" />
    <EmbeddedResource Remove="Protobuf-**/**" />
    <None Remove="Protobuf-*/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="EggEgg.CSharp-Logger" Version="5.0.0" />
    <PackageReference Include="EggEgg.Shell" Version="5.0.0-rc15" />
    <PackageReference Include="EggEgg.XC.RSAUtil" Version="136.1.1" />
    <PackageReference Include="Google.Protobuf" Version="3.27.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NJsonSchema" Version="11.0.1" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
    <PackageReference Include="TextCopy" Version="6.2.1" />
    <PackageReference Include="Grpc.Tools" Version="2.64.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protobuf-$(protobuf_version)/*.proto" ProtoRoot="Protobuf-$(protobuf_version)" GrpcServices="None" />
    <Protobuf Include="Protobuf-$(protobuf_version)/Protos/*.proto" ProtoRoot="Protobuf-$(protobuf_version)/Protos" GrpcServices="None" />
  </ItemGroup>

</Project>
