name: EasyProtobuf Publish Test

on:
  push:
    branches: [ "main", "actions-test" ]
  pull_request:
    branches: [ "main" ]

jobs:

  publish-windows:

    strategy:
      matrix:
        protobuf-branch: [
          "hk4e_3.4_gio-cmdid",
          "hk4e_3.4_live",
        ]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Publish EasyProtobuf
      run: .\publish.ps1 $env:ProtobufBranch
      env:
        ProtobufBranch: ${{ matrix.protobuf-branch }}

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EasyProtobuf Builds (Windows)
        path: EasyProtobuf Build

  publish-ubuntu:

    strategy:
      matrix:
        protobuf-branch: [
          "hk4e_3.4_gio-cmdid",
          "hk4e_3.4_live",
        ]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Fetch Protobuf and Publish EasyProtobuf
      run: |
        git clone --branch $env:ProtobufBranch https://github.com/YYHEggEgg/mihomo-protos Protobuf-$env:ProtobufBranch
        ./publish $env:ProtobufBranch
      env:
        ProtobufBranch: ${{ matrix.protobuf-branch }}

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EasyProtobuf Builds (Ubuntu)
        path: EasyProtobuf Build
